version: '3.9'
services:

  ## Service NodeExporter :: Metrics Gathering (from current host)
  node-exporter:
    container_name: node-exporter
    hostname: monitoring
    image: prom/node-exporter:v${NODE_EXPORTER_VERSION}
    ports:
      - 127.0.0.1:9100:9100
    networks:
      - default
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points"
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    environment:
      #- TZ=Asia/Omsk
      TZ: "Asia/Omsk"
    restart: unless-stopped


  ## Service BlackBoxExporter :: WebServices Monitoring (with http, https, tcp, udp, etc. protocols)
  blackbox-exporter:
    container_name: blackbox-exporter
    hostname: blackbox
    image: prom/blackbox-exporter:v${BLACKBOX_EXPORTER_VERSION}
    ports:
      - 127.0.0.1:9115:9115
    networks:
      - default
    volumes:
      - ./blackbox:/etc/blackbox
    command:
      - "--config.file=/etc/blackbox/blackbox.yaml"
    environment:
      TZ: "Asia/Omsk"
    restart: unless-stopped

  ## Service Prometheus :: Metrics Collecting, Storing and Processing
  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus:v${PROMETHEUS_VERSION}
    ports:
      - 127.0.0.1:9090:9090
    networks:
      - default
    volumes:
      - ./prometheus:/etc/prometheus
      - vol-prometheus:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--web.external-url=/mon/prom"
      - "--web.route-prefix=/"
    environment:
      TZ: "Asia/Omsk"
    links:
      - cadvisor:cadvisor
    depends_on:
      - node-exporter
      - cadvisor
    restart: unless-stopped

  ## Service AlertManager :: Metrics Changes Triggering and Sending Alerts
  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:v${ALERTMANGER_VERSION}
    ports:
      - 127.0.0.1:9093:9093
    networks:
      - default
    volumes:
      - ./alertmanager:/etc/alertmanager
      - ../_secrets:/etc/alertmanager/_secrets
      - vol-alertmanager:/alertmanager
      - /etc/localtime:/etc/localtime:ro
    command:
      - --config.file=/etc/alertmanager/alertmanager.yaml
      - --storage.path=/alertmanager/data
    environment:
      TZ: "Asia/Omsk"
    depends_on:
      - node-exporter
      - prometheus
    restart: unless-stopped

  ## Service cAdvisor :: WebApp for Docker Containers
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v${CADVISOR_VERSION}
    ports:
      - 127.0.0.1:8088:8080
    networks:
      - default
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/kmsg:/dev/kmsg
    privileged: true
    command: 
      - "--docker_only=true"
      - "--housekeeping_interval=30s"
      - "--disable_metrics=percpu,sched,tcp,udp,disk,diskIO,accelerator,hugetlb,referenced_memory,cpu_topology,resctrl"
    environment:
      TZ: "Asia/Omsk"
    depends_on:
      - redis
    restart: unless-stopped

  ## Service Redis :: In-memory key-value Database and Message Broker (cAdvisor dependency)
  redis:
    container_name: redis
    image: redis:${REDIS_VERSION}
    ports:
      - 127.0.0.1:6379:6379
    networks:
      - default
    volumes:
      - vol-redis:/data
    restart: unless-stopped


  ## Service Portainer :: WebApp for Local and Remote Docker Environments (as "Docker Desktop" for Windows)
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:${PORTAINER_VERSION}
    ports:
      - "9000:9000/tcp"
      #- 127.0.0.1:9000:9000/tcp
    networks:
      - default
    #sysctls:
    #  - net.ipv6.conf.all.disable_ipv6=1           ## disabling ipv6 doesnt work
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - vol-portainer:/data
    environment:
      #- TZ=Asia/Omsk
      TZ: "Asia/Omsk"
    restart: unless-stopped


  ## Service Grafana :: WebApp for metrics visualisation (like Zabbix)
  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana:${GRAFANA_VERSION}
    ##..if you are running as "root" then set it to 0 else find the right id with the id -u command
    user: root
    #user: '0'
    ports:
      #- 3000:3000
      - 127.0.0.1:3000:3000
    networks:
      - default
    volumes:
      - vol-grafana:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro
      #- ./grafana:/var/lib/grafana
      #- ./grafana/datasources:/etc/grafana/datasources    ## doesnt work
      #- ./grafana/dashboards:/etc/grafana/dashboards      ## doesnt work
      #- ./grafana/setup.sh:/setup.sh                      ## doesnt work
    #
    #entrypoint: /setup.sh                                 ## doesnt work
    environment:
      - TZ=Asia/Omsk
      - GF_SERVER_ROOT_URL=${GRAFANA_ENDPOINT:-/grafana}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_LOGIN:-devops}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PSSWD:-devops}
      #
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_METRICS_ENABLED=false
      - GF_INSTALL_PLUGINS=grafana-clock-panel, grafana-simple-json-datasource
      - GF_FEATURE_TOGGLES_ENABLE=publicDashboards
      #
    depends_on:
      - prometheus
    restart: unless-stopped


## Persistent Volumes for Services
volumes:
  vol-grafana: {}
  vol-prometheus:
  vol-alertmanager:
  vol-portainer:
  vol-redis:


## Network configuration
## *disabling IPv6 may result problems in starting some containers
##  https://github.com/docker/compose/issues/4958
##  - enable_ipv6 option is not allowed:
##    Network configuration in v3 is currently more limited until Swarm mode is able to support more advanced configurations
#
networks:
  default:
    ipam:
      driver: default           ## bridge|default
      #enable_ipv6: false       ## ERROR: Additional property enable_ipv6 is not allowed
      config:
        - subnet: 172.28.0.0/16
