version: '3.2'
services:

  ## Service NodeExporter :: Collects Metrics (from current host)
  node-exporter:
    hostname: monitoring
    image: prom/node-exporter
    ports:
      - 127.0.0.1:9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --web.telemetry-path=/exporter/metrics/
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points
      - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
    restart: always
