services:
  #
  webapp1:
    container_name: webapp1
    build:
      context: app1
      target: builder
    ##
    ##..flask requires SIGINT to stop gracefully
    ##  default stop signal from Compose is SIGTERM
    stop_signal: SIGINT
    ports:
      - '8001:8000'
    restart: unless-stopped
  #
  webapp2:
    container_name: webapp2
    build:
      context: app2
      target: builder
    stop_signal: SIGINT
    ports:
      - '8002:8000'
    restart: unless-stopped
